### ISSUE TITLE
Binary sensor stays on when the door is closed

### ISSUE THREAD

**Issue by MudiW** [wernerhp/appdaemon_wasp#3]
Even though

box: off
wasp: off

The binary sensor stays on when the door is closed, even though there was no movement after closing the door

Awesome app btw.

**Comment by wernerhp** [comment]
Try setting `delay: 5` 
Your sensor may be detecting movement before the door is closed, so wasp turns on briefly before box is off. This sets and locks the binary sensor to on. The wasp no longer moves, so wasp changes to off, however we think there's a wasp in the box because it moved before the box was closed. Delay should allow the wasp to reset. It depends on how long your sensor remains on.  My sensors detect movement every 5s, so a 5s delay solves this for me.

https://github.com/wernerhp/appdaemon_wasp/blob/master/README.md

**Comment by ahmaddxb** [comment]
@wernerhp what sensors do you use?

**Comment by wernerhp** [comment]
Xiaomi /Aqara Door and Motion Sensors with the hardware and software mods so they detect motiin every 5s.

**Comment by pterodaktil02** [comment]
same  problem 

motion sensor  have  delay 10  sec and it do not turn off wasp sensor.  config   of wasp sensor
```
tualet_wasp:
  module: wasp
  class: Wasp
  device_class: occupancy
  name: Туалет присутствие
  delay: 10
  box_sensors:
    - binary_sensor.tualet_door_contact
  wasp_sensors:
    - binary_sensor.tualet_occupancy
```
It turn  wasp on  perfectly
but   do  not turn  off  it at all

**Comment by marckanneg** [comment]
Hey i just had an similar issue usinq "hacked" aqara sensors. 

The "issue" is, that the code checks the wasp-state after the delay and if the occupancy is still "on" at that time the wasp is considered in the box. My occupancy_timeout is configured somewhere between 15 to 45 seconds (even if the sensors trigger zigbee events every 5s). so I have to set the delay accordingly to the may occupancy_timeout within my wasp-sensors. 

maybe that helps ;)

**Comment by wernerhp** [comment]
Do you have the hardware and software mods for the Aqara sensors or just the hardware mod?

https://github.com/wernerhp/appdaemon_aqara_motion_sensors/

**Comment by sym0nd0** [comment]
Hi all,
I have the same issue - Aqara Motion Sensor (RTCGQ11LM) modified to reduce cool down time and Aqara door & window contact sensor (MCCGQ11LM).

I have both Wasp in a box and Aqara Motion Sensors AppDaemon apps installed and configured:
```
# Wasp in a box automation
bathroom_wasp:
  module: wasp
  class: Wasp
  device_class: occupancy
  name: Washroom Occupancy
  delay: 5
  box_sensors:
    - binary_sensor.contact_sensor_washroom_door_contact
  wasp_sensors:
    - binary_sensor.motion_sensor_washroom_occupancy

# Aqara Motion Sensor reset automation
aqara:
  module: aqara
  class: Aqara
  timeout: 5
  motion_sensors:
    - binary_sensor.motion_sensor_washroom_occupancy
```
As you can see, sensor remained on for nearly 12 hours, yet the room wasn't occupied during that period.
![image](https://user-images.githubusercontent.com/55590428/162564443-37474bed-e8d5-4b9f-bcfa-967f1289cf5e.png)

Any ideas how to resolve this? Apologies if it's something really simple that I've missed or messed up.

**Comment by dersch81** [comment]
Same for me

![image](https://github.com/wernerhp/ha.appdaemon.wasp/assets/13754891/b7acc316-ec4b-4c4f-ae12-1dfdfe1f25a8)

```
guestwc_wasp:
  module: wasp
  class: Wasp
  device_class: occupancy
  name: GuestWC Occupancy
  delay: 5
  box_sensors:
    - binary_sensor.gastewc_tur
  wasp_sensors:
    - binary_sensor.gastewc_bewegung
    - binary_sensor.gastewc_klositz
```

Using custom mqtt sensors: reed contact at the door, motion sensor and reed contact inside the toilet seat to know if it is open or closed.
